# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default

steps:
- script: echo My first Azure Pipeline for Gradle project
  displayName: 'Run a one-line script'

- script: ./gradlew build
  displayName: 'Build with Gradle'

- script: ./gradlew run
  displayName: 'Run JAR'
  
- script: java -jar gradle-wrapper.jar
  displayName: 'This is the output of this project'