# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  name: Default   

steps:
  - task: Gradle@3
    displayName: 'Build with Gradle Wrapper'
    inputs:
      gradleWrapperFile: 'gradlew'            # points at your wrapper script
      tasks: 'clean build'                    # or whatever tasks you need
      options: '-Xmx3072m --no-daemon'        # heap and no‑daemon flags
      publishJUnitResults: true
      testResultsFiles: '**/build/test-results/**/*.xml'
      javaHomeOption: 'JDKVersion'            # pick a JDK by version
      jdkVersionOption: '17.0'                  # matches JAVA_HOME_17_X64
      jdkArchitectureOption: 'x64'

