# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - main

pool:
  name: Default

steps:
  - script: |
      sudo apt-get update
      sudo apt-get install -y openjdk-17-jdk
      echo "##vso[task.setvariable variable=JAVA_HOME_17_X64]/usr/lib/jvm/java-17-openjdk-amd64"
    displayName: 'Install JDK 17'

  - task: Gradle@3
    displayName: 'Build with Gradle Wrapper'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'clean build'
      options: '-Xmx3072m --no-daemon'
      publishJUnitResults: true
      testResultsFiles: '**/build/test-results/**/*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '17'
      jdkArchitectureOption: 'x64'
